pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Python Test"'
                sh '''
                    python3 print(3*3)
                '''
            }
        }
    }
}